<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RequirementsNegociation" nsURI="mde.ecore.rn" nsPrefix="rn">
  <eClassifiers xsi:type="ecore:EClass" name="Negotiation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholders" upperBound="-1"
        eType="#//Stakeholder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propositions" upperBound="-1"
        eType="#//Proposition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stakeholder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proposition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposedBy" lowerBound="1"
        upperBound="-1" eType="#//Stakeholder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WinCondition" eSuperTypes="#//Proposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" containment="true" eOpposite="#//Issue/referencedProposition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Issue" eSuperTypes="#//Proposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProposition"
        lowerBound="1" eType="#//WinCondition" eOpposite="#//WinCondition/issues"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option" eSuperTypes="#//Proposition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedIssue" lowerBound="1"
        eType="#//Issue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="votes" upperBound="-1"
        eType="#//Vote" containment="true" eOpposite="#//Vote/option"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vote">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreement" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importance" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stakeholder" lowerBound="1"
        eType="#//Stakeholder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="option" lowerBound="1"
        eType="#//Option" eOpposite="#//Option/votes"/>
  </eClassifiers>
</ecore:EPackage>
